import React from 'react';
export type IconComponentType = React.FC<React.SVGProps<SVGSVGElement>>;

export { default as OrderedListOutlined } from './OrderedListOutlined';
export { default as UnorderedListOutlined } from './UnorderedListOutlined';
export { default as TextBoldOutlined } from './TextBoldOutlined';
export { default as TextItalicOutlined } from './TextItalicOutlined';
export { default as TextUnderlineOutlined } from './TextUnderlineOutlined';
export { default as MentionOutlined } from './MentionOutlined';
export { default as FileOutlined } from './FileOutlined';
export { default as TextNormalOutlined } from './TextNormalOutlined';
export { default as Heading1Outlined } from './Heading1Outlined';
export { default as Heading2Outlined } from './Heading2Outlined';
export { default as Heading3Outlined } from './Heading3Outlined';
export { default as QuoteBlockOutlined } from './QuoteBlockOutlined';
export { default as ExpandOutlined } from './ExpandOutlined';
export { default as TextColorOutlined } from './TextColorOutlined';
export { default as BackgroundColorOutlined } from './BackgroundColorOutlined';
export { default as FontSizeOutlined } from './FontSizeOutlined';
export { default as AlignLeftOutlined } from './AlignLeftOutlined';
export { default as AlignCenterOutlined } from './AlignCenterOutlined';
export { default as AlignRightOutlined } from './AlignRightOutlined';
export { default as AlignJustifyOutlined } from './AlignJustifyOutlined';
export { default as LinkOutlined } from './LinkOutlined';
